# -*- coding: utf-8 -*-
# Generated by Django 1.10.2 on 2016-10-20 13:49
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='colaborador',
            options={'verbose_name_plural': 'Colaboradores'},
        ),
        migrations.AlterModelOptions(
            name='relogioponto',
            options={'verbose_name': 'rel\xf3gio de ponto', 'verbose_name_plural': 'rel\xf3gios de ponto'},
        ),
        migrations.AddField(
            model_name='relogioponto',
            name='nome',
            field=models.CharField(default='', max_length=30),
            preserve_default=False,
        ),
    ]
