# -*- coding: utf-8 -*-
# Generated by Django 1.10.2 on 2016-10-20 22:49
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_auto_20161020_1149'),
    ]

    operations = [
        migrations.AlterField(
            model_name='parametro',
            name='propriedade',
            field=models.CharField(editable=False, max_length=25),
        ),
        migrations.AlterField(
            model_name='parametro',
            name='tipo',
            field=models.CharField(default='str', editable=False, max_length=25),
        ),
    ]
