# -*- coding: utf-8 -*-
# Generated by Django 1.10.2 on 2016-10-25 21:31
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_auto_20161020_2049'),
    ]

    operations = [
        migrations.CreateModel(
            name='RegistroPonto',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('data_hora', models.DateTimeField()),
            ],
        ),
        migrations.AlterModelOptions(
            name='colaborador',
            options={'verbose_name_plural': 'colaboradores'},
        ),
        migrations.AlterModelOptions(
            name='parametro',
            options={'verbose_name': 'par\xe2metro'},
        ),
        migrations.AlterField(
            model_name='colaborador',
            name='pis',
            field=models.CharField(max_length=25, unique=True, verbose_name='PIS'),
        ),
        migrations.AlterField(
            model_name='matricula',
            name='colaborador',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='matriculas', to='core.Colaborador'),
        ),
        migrations.AlterField(
            model_name='matricula',
            name='numero',
            field=models.IntegerField(verbose_name='n\xfamero'),
        ),
        migrations.AlterField(
            model_name='parametro',
            name='relogio',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='parametros', to='core.RelogioPonto', verbose_name='rel\xf3gio'),
        ),
        migrations.AddField(
            model_name='registroponto',
            name='colaborador',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.Colaborador'),
        ),
        migrations.AddField(
            model_name='registroponto',
            name='relogio',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.RelogioPonto'),
        ),
    ]
