# -*- coding: utf-8 -*-
# Generated by Django 1.10.2 on 2016-10-27 21:20
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_auto_20161025_1931'),
    ]

    operations = [
        migrations.CreateModel(
            name='PadraoExportacao',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('parametro', models.CharField(max_length=15)),
                ('formato', models.CharField(max_length=100)),
            ],
        ),
    ]
