# -*- coding: utf-8 -*-
# Generated by Django 1.10.2 on 2016-11-21 21:15
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0006_auto_20161121_1214'),
    ]

    operations = [
        migrations.DeleteModel(
            name='PadraoExportacao',
        ),
    ]
