# -*- coding: utf-8 -*-
# Generated by Django 1.10.2 on 2016-12-02 09:50
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0009_auto_20161201_1208'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='registroponto',
            options={'verbose_name': 'registro de ponto', 'verbose_name_plural': 'registros de ponto'},
        ),
        migrations.AlterField(
            model_name='registroponto',
            name='colaborador',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='registros', to='core.Colaborador'),
        ),
        migrations.AlterField(
            model_name='registroponto',
            name='data_hora',
            field=models.DateTimeField(verbose_name='data do registro'),
        ),
        migrations.AlterField(
            model_name='registroponto',
            name='exportado',
            field=models.BooleanField(default=False, verbose_name='registro exportado'),
        ),
        migrations.AlterField(
            model_name='registroponto',
            name='relogio',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.RelogioPonto', verbose_name='rel\xf3gio'),
        ),
    ]
