# -*- coding: utf-8 -*-
# Generated by Django 1.10.2 on 2017-03-20 08:02
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0010_auto_20161202_0950'),
    ]

    operations = [
        migrations.AlterField(
            model_name='colaborador',
            name='verificar_digital',
            field=models.BooleanField(default=True),
        ),
        migrations.AlterField(
            model_name='relogioponto',
            name='tipo',
            field=models.IntegerField(choices=[(1, b'Henry - Prisma'), (2, b'Henry - Orion V (usando database do programa host)')]),
        ),
    ]
