# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-05-16 17:20
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0011_auto_20170320_0802'),
    ]

    operations = [
        migrations.AddField(
            model_name='relogioponto',
            name='ativo',
            field=models.BooleanField(default=True),
        ),
    ]
