# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-05-16 20:16
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0012_relogioponto_ativo'),
    ]

    operations = [
        migrations.AlterField(
            model_name='colaborador',
            name='nome',
            field=models.CharField(help_text='Nome completo do colaborador', max_length=100),
        ),
        migrations.AlterField(
            model_name='colaborador',
            name='pis',
            field=models.CharField(help_text='N\xfamero do PIS (somente n\xfameros)', max_length=25, unique=True, verbose_name='PIS'),
        ),
        migrations.AlterField(
            model_name='colaborador',
            name='verificar_digital',
            field=models.BooleanField(default=True, help_text='Selecione se a pessoa ter\xe1 ou n\xe3o que fazer uma autentica\xe7\xe3o biom\xe9trica ao cadastrar'),
        ),
        migrations.AlterField(
            model_name='registroponto',
            name='relogio',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='core.RelogioPonto', verbose_name='rel\xf3gio'),
        ),
        migrations.AlterField(
            model_name='relogioponto',
            name='ativo',
            field=models.BooleanField(default=True, help_text='Indica se o rel\xf3gio est\xe1 ativado, conectado e/ou ligado \xe0 rede'),
        ),
        migrations.AlterField(
            model_name='relogioponto',
            name='nome',
            field=models.CharField(help_text='Um nome simples para identificar o rel\xf3gio', max_length=30),
        ),
    ]
